name: crclib
version: 2.0.0
authors:
  - Nam T. Nguyen <namnguyen@google.com>
description: Collection of cyclic redundancy check (CRC) routines as Dart converters.
homepage: https://github.com/google/crclib.dart
dependencies:
  meta: ">=1.3.0-nullsafety.6 <2.0.0"
  tuple: ">=2.0.0-nullsafety.0 <3.0.0"
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  path: ">=1.8.0-nullsafety.3 <2.0.0"
  pedantic: "^1.9.0"
  test: ">=0.16.0-nullsafety.16 <2.0.0"
