name: crclib
version: 1.1.0
authors:
  - Nam T. Nguyen <namnguyen@google.com>
description: Collection of cyclic redundancy check (CRC) routines as Dart converters.
homepage: https://github.com/google/crclib.dart
dependencies:
  meta: ">=1.0.2 <2.0.0"
  tuple: ">=1.0.0 <2.0.0"
environment:
  sdk: ">=1.20.0 <3.0.0"
dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  path: any
  pedantic: "^1.9.0"
  test: ">=0.12.20 <2.0.0"
